In [2]:
#functions such as:
#1. numpy.reshape(array, newshape,...)Note: this can also work as array.reshape (coz functions can work as methods in numpy)
#2. numpy.ndarray.flatten(array) OR np.ravel(array) OR array.ravel()
#3. Concatenate
#4. transpose
#5. sort

#explore more such functions to become champ

In [4]:
import numpy as np
array_1=np.array([1,2,3,4,5,6,4,2,2,1])
array_2=np.array([[2,3,4,5,6],[5,6,3,2,4]])

In [9]:
array_1

array([1, 2, 3, 4, 5, 6, 4, 2, 2, 1])

In [10]:
array_1.shape #or np.shape(array_1)...also note shape when called as method, does not need '()'

(10,)

In [12]:
np.shape(array_1)

(10,)

In [6]:
array_2

array([[2, 3, 4, 5, 6],
       [5, 6, 3, 2, 4]])

In [13]:
np.shape(array_2)

(2, 5)

In [14]:
#now, if we have to reshape array_1 to 2d array..
#we will use reshape function
#np.reshape(a,newshape,..) a=array, newshape=tuple of integers, ...can be other arguments if needed

#now lets try

In [15]:
array_1

array([1, 2, 3, 4, 5, 6, 4, 2, 2, 1])

In [17]:
np.reshape(array_1,(2,5)) #basically converting array_1 to(2,5) shape

array([[1, 2, 3, 4, 5],
       [6, 4, 2, 2, 1]])

In [19]:
#using reshape as method
array_1.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [6, 4, 2, 2, 1]])

In [20]:
#lets see what happens if we pass inconsitent conversion request
np.reshape(array_1,(2,6))

ValueError: cannot reshape array of size 10 into shape (2,6)

In [21]:
#so you see shape has to be consistent, we can not shape it to (2,6)

In [22]:
#so to keep a note here is array should have #of element = row*column size
#since array_1 has 10 element and we want 2*6=12 size, this is inconsistent

In [23]:
#also this reshaping(transformarion) does NOT happen in orinial array. So, array_1 is same as before (as 1d array)

array_1

array([1, 2, 3, 4, 5, 6, 4, 2, 2, 1])

In [25]:
#now, faltten and ravel function (basically flattens the 2d array to 1 array), lets see

In [26]:
array_2

array([[2, 3, 4, 5, 6],
       [5, 6, 3, 2, 4]])

In [27]:
np.flatten(array_2)

AttributeError: module 'numpy' has no attribute 'flatten'

In [28]:
#hmm, dont use np.flatten...use np.ndarray.flatten (or np.ravel)

In [29]:
np.ndarray.flatten(array_2)

array([2, 3, 4, 5, 6, 5, 6, 3, 2, 4])

In [38]:
#or using flatten as method
array_2.flatten()

array([2, 3, 4, 5, 6, 5, 6, 3, 2, 4])

In [30]:
#cool, also it doesn;t change the original array (so array_2) remains same:
array_2

array([[2, 3, 4, 5, 6],
       [5, 6, 3, 2, 4]])

In [31]:
#we can achieve same thing with ravel
np.ravel(array_2)

array([2, 3, 4, 5, 6, 5, 6, 3, 2, 4])

In [32]:
#so no '.ndarray' needed

In [34]:
#we can also do it by using ravel as method
array_2.ravel()

array([2, 3, 4, 5, 6, 5, 6, 3, 2, 4])

In [39]:
#concatenate function
#np.concatenate((array_1,array_2),axis=?,..)  define arrays that are be concatenated in tuple, then define axis (1 or 0)
#default axis is 0 -axis

#imp1: if concatenating on 0 axis, shape must have same column. think it this way that you are adding a new row/rows....
#        ...so it make sense to add row with same columns

#imp2: if concatenating on 1 axis, shape must have same rows. think it this way that you are adding a new column/columns....
#        ...so it make sense to add columns in existing rows

In [44]:
#lets redefine/create array_1, array_2 and array_3

In [45]:
array_1=np.array([[1,1,1],[2,2,2]])

In [48]:
array_2=np.array([[3,3,3],[4,4,4],[5,5,5]])

In [49]:
array_3=np.array([[3,3],[4,4],[5,5]])

In [50]:
array_1.shape

(2, 3)

In [51]:
array_2.shape

(3, 3)

In [52]:
array_3.shape

(3, 2)

In [53]:
#so looking at the shapes and 'gyan' from [39] on concatenation, array_1 & array_2 can be concat for axis 0...
#..i.e. array_2 will be added as a new row in array_1, well, lets do it

In [54]:
np.concatenate((array_1, array_2), axis=0) 

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [55]:
np.concatenate((array_1, array_2)) #by default axis is 0

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [56]:
#so you see, same result in [54] & [55] as by default axis is 0

In [57]:
#if we change axis =1, it wont work

In [58]:
np.concatenate((array_1, array_2), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [59]:
#at axis=1 above, we get something like this, so this scenerio is not possible
# 1,1,1,3,3,3
# 2,2,2,4,4,4
#      ,5,5,5

In [60]:
array_1.concatenate(array_2)

AttributeError: 'numpy.ndarray' object has no attribute 'concatenate'

In [ ]:
#hmm, concatenate needs multiple arguments, so may be thats why it wont work like this

In [61]:
#similarly, we can concatenate array_1 with array_2 (jut reverse the order of arrays)

np.concatenate((array_2, array_1), axis=0)

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [1, 1, 1],
       [2, 2, 2]])

In [62]:
#lets look at array_2 and array_3, first lets call them again for visibility

In [63]:
array_2

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [64]:
array_3

array([[3, 3],
       [4, 4],
       [5, 5]])

In [65]:
array_2.shape

(3, 3)

In [66]:
array_3.shape

(3, 2)

In [ ]:
#so looking at these array, it is visible that this concatenation can only happen on column (so axis=1)


In [68]:
np.concatenate((array_2, array_3), axis=1)

array([[3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [ ]:
#...but lets try axis=0 for fun

In [69]:
np.concatenate((array_2, array_3), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
#hmm, error was expected coz this scenerio is not possible:

#at axis=1 above, we get something like this, so this scenerio is not possible

# 3,3,3
# 4,4,4
# 5,5,5
# 3,3,
# 4,4
# 5,5

#looks bad

In [70]:
array_1

array([[1, 1, 1],
       [2, 2, 2]])

In [71]:
array_3

array([[3, 3],
       [4, 4],
       [5, 5]])

In [72]:
array_1.shape

(2, 3)

In [73]:
array_3.shape

(3, 2)

In [ ]:
#so nothing works between array_1 and array_3 for concatenation

In [74]:
#transpose function (to inverse the rows into columns)..(row1 becomes column1, row2 becomes column2...so on)
#np.transpose(array)

In [75]:
array_1

array([[1, 1, 1],
       [2, 2, 2]])

In [76]:
np.transpose(array_1) #or use array_1.transpose()

array([[1, 2],
       [1, 2],
       [1, 2]])

In [78]:
array_1.transpose()

array([[1, 2],
       [1, 2],
       [1, 2]])

In [79]:
#sort function
#np.sort(array,axis=-1..) default axis is -1, which is the last axis

In [5]:
#example
array_unsort=np.array([[1,10,3],[2,3,1]])
array_unsort

array([[ 1, 10,  3],
       [ 2,  3,  1]])

In [82]:
#so sorting around axis=0 (which means sort on columns, as axis 0 goes south (column-vise), shd result in

# 1,3,1
# 2,10,3

#and sorting around axis=1 (which means sort on rows), shd result in

# 1,3,10
# 1,2,3

#lets see

In [83]:
np.sort(array_unsort, axis=0)

array([[ 1,  3,  1],
       [ 2, 10,  3]])

In [84]:
np.sort(array_unsort,axis=1)

array([[ 1,  3, 10],
       [ 1,  2,  3]])

In [85]:
np.sort(array_unsort) #by default sort is on axis1 (row sort)

array([[ 1,  3, 10],
       [ 1,  2,  3]])

In [7]:
sd=array_unsort.sort(axis=0)

In [8]:
sd

In [ ]:
#above 2 rows didn't work like that