In [ ]:
#creation function

#6. np.full(shape_as_in_tuple, fill_value_to_fill_array, dtype)
#7. np.arange(start_default_is_0, stop_this_is_exclusive, step_default_is_1, ....)
#8. np.linspace(start, stop, totalcount_of_number,...)
#9. np.random.rand(rows,columns)
#10. np.random.randint(low_bound, high_bound, shape_tuple, dtype)

#homework (look into the course resource)
#11. np.identity
#12. np.zeros
#13. np.ones

In [1]:
#full function to create array

#np.full(shape(2,3), fill_value,dtype,...) 
#Shape is given as tuple,fill value is what will fill in the tuple, dtype=datatype of array

In [2]:
array_1=np.full((2,5),2) #so this will fill value '2' across 2 rows & 5 column.

NameError: name 'np' is not defined

In [3]:
#hmm, coz we hav NOT imported numpy yet :(

In [5]:
import numpy as np

array_1=np.full((2,5),2)
array_1

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [6]:
#lets create another array with fill value of 0, with dtype of longdouble, shape of 5*5...lets create

In [7]:
array_2=np.full((5,5),0,'g') #by-default position of the arguments
array_2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float64)

In [8]:
#if arguments are moved around, then call them by name(i.e.specify the argument)

array_2=np.full((5,5), dtype=np.longdouble, fill_value=0)
array_2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float64)

In [10]:
#also we can do this way (arguments position again chaged, but addressed by name)

array_2=np.full(dtype=np.longdouble, shape=(5,5), fill_value=0)
array_2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float64)

In [ ]:
#see, same result in [7], [8], [10]

In [11]:
#arange function (note: arange is not arrange or sort, its kind of a-range)
#np.arange(start_default_0, stop_exclusive, step_default_1, dtype,....additional parameters..)

In [13]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
#if we need to shape (or reshape) this array in (2,3) metric, then do:

np.arange(0,12,2).reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [16]:
# OR if we need to shape (or reshape) this array in (3,2) metric, then do:

np.arange(0,12,2).reshape(3,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [17]:
#linspace function (create evenly spaced array over the given irange)

#np.linspace(start,stop_inclusive_here,num=50, dtype..other params..)

#so here its creating an array with 50 elements which would be evenly spaced, lets see

In [24]:
np.linspace(1,50,18)

array([ 1.        ,  3.88235294,  6.76470588,  9.64705882, 12.52941176,
       15.41176471, 18.29411765, 21.17647059, 24.05882353, 26.94117647,
       29.82352941, 32.70588235, 35.58823529, 38.47058824, 41.35294118,
       44.23529412, 47.11764706, 50.        ])

In [25]:
#plz note: above array is still 1d, although it looks like 2d, oz its a long array, lets check the shape

np.linspace(1,50,18).shape

(18,)

In [26]:
#we can reshape it in (3,6) or (6,3) too, lets do it:

In [28]:
np.linspace(1,50,18).reshape(3,6)

array([[ 1.        ,  3.88235294,  6.76470588,  9.64705882, 12.52941176,
        15.41176471],
       [18.29411765, 21.17647059, 24.05882353, 26.94117647, 29.82352941,
        32.70588235],
       [35.58823529, 38.47058824, 41.35294118, 44.23529412, 47.11764706,
        50.        ]])

In [29]:
#reshaping in (6,3)

np.linspace(1,50,18).reshape(6,3)

array([[ 1.        ,  3.88235294,  6.76470588],
       [ 9.64705882, 12.52941176, 15.41176471],
       [18.29411765, 21.17647059, 24.05882353],
       [26.94117647, 29.82352941, 32.70588235],
       [35.58823529, 38.47058824, 41.35294118],
       [44.23529412, 47.11764706, 50.        ]])

In [32]:
#jlt

np.linspace(1,10,num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
#random function to create array
#np.random.rand(rows,colmn)--generates random values between 0-1
#np.random.randint(low_bound, high_bound, shape_tuple,dtype, ..)

In [35]:
np.random.rand(3,4)

array([[0.47909495, 0.02872147, 0.37672372, 0.12837681],
       [0.58315854, 0.55269244, 0.27956777, 0.04841561],
       [0.34746966, 0.774943  , 0.49865201, 0.25849109]])

In [40]:
#so it look likes random.randint would be more meaningful, lets see

#generating array between -20 to 20 (of 4 by 10)

In [42]:
np.random.randint(-20,20,(4,10))

array([[-13,  -1,  17,  -9,  15,  16,  17,   2,   7,   6],
       [ 12,   9,  -8,  14, -12, -19,  -7,   6,  15,  12],
       [ 11,   1,  14, -17,  12,  16,   2,  -4,  15,  11],
       [-18, -19, -13, -20,   4,   9, -13,   8,  11,   3]])

In [43]:
#hence a radom array is generate of size (4,10) with numbers between -20 to 20

In [44]:
#homework, research: 

#np.identity
#np.zeros
#np.ones

In [45]:
np.identity(3) #3 means return 3*3 (i.e. n by n array)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.identity (10) #10 by 10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [47]:
#np.ones - creates the array with value=1 in specified shape and size and data type (but all elements are 1)

#np.ones(shape_tuple_or_int,dtype,order='C' or 'F',*,like=None)

np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
#np.zeros - creates the array with value=0 in specified shape and size and data type (but all elements are 0)

#np.zeros(shape_tuple_or_int,dtype,order='C' or 'F',*,like=None)

In [51]:
np.zeros(3)

array([0., 0., 0.])

In [52]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])