In [1]:
#1. add or +
#2. learn about broadcast
#3. substract or -
#4. multiply or divide by scalar value
#5. np.sum
#6. np.cumsum
#7. np.mean OR array.mean()
#8. np.amax
#9. np.amin
#10. np.std() ---std deviation

In [2]:
import numpy as np

In [5]:
array_1=np.array([[1,2,3,3,3]])

In [9]:
array_2=np.array([1,2,3,4,5,5,3,2,4,2,1,2,3,4,5]).reshape(5,3)

In [10]:
array_3=np.array([1,2,3,4,5,5,3,2,4,2,1,2,3,4,5]).reshape(3,5)

In [11]:
array_1

array([[1, 2, 3, 3, 3]])

In [12]:
array_2

array([[1, 2, 3],
       [4, 5, 5],
       [3, 2, 4],
       [2, 1, 2],
       [3, 4, 5]])

In [13]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [14]:
#now, if you see here array_2 and array_3 have same element but just reshaped differently - (5,3) and (3,5)

In [15]:
#add 2 arrays, just use '+'

array_1 + array_1

array([[2, 4, 6, 6, 6]])

In [16]:
#each element in array_1 is added to each corresponding element in array_1 (concept of broadcasting)

In [17]:
#add function - we can also use add function (only limitation is that it takes 2 argument only, so we cant 'add' 3 arrays)

In [19]:
np.add(array_1, array_1)

array([[2, 4, 6, 6, 6]])

In [20]:
# lets see what happens if we use array_1 and array_2

In [21]:
np.add(array_1, array_2)

ValueError: operands could not be broadcast together with shapes (1,5) (5,3) 

In [22]:
#this is because they have different #of columns (basically different shape), so each element of array1 couldn't be broadcasted....
#....to corresponding element of array_2

#this shoudl work for adding array_1 and array_3

In [23]:
array_1

array([[1, 2, 3, 3, 3]])

In [24]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [25]:
np.add(array_1, array_3)

array([[2, 4, 6, 7, 8],
       [6, 5, 5, 7, 5],
       [2, 4, 6, 7, 8]])

In [26]:
#cool, we can also get it by simple '+' sign too

array_1 + array_3

array([[2, 4, 6, 7, 8],
       [6, 5, 5, 7, 5],
       [2, 4, 6, 7, 8]])

In [27]:
#now, lets see substraction

array_1 - array_3

array([[ 0,  0,  0, -1, -2],
       [-4, -1,  1, -1,  1],
       [ 0,  0,  0, -1, -2]])

In [28]:
array_3 - array_1

array([[ 0,  0,  0,  1,  2],
       [ 4,  1, -1,  1, -1],
       [ 0,  0,  0,  1,  2]])

In [35]:
#or use np.subtract (note: subtract not substract)

np.subtract(array_3, array_1)

array([[ 0,  0,  0,  1,  2],
       [ 4,  1, -1,  1, -1],
       [ 0,  0,  0,  1,  2]])

In [29]:
#so we saw substraction works too the same way

In [30]:
#similarly, we can broadcast an integer value too (lets see few examples)

In [31]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [32]:
#adding scaler value of 5 will broadcast 5 to each elemnt of array_3 (each element in array_3 will increase by 5)

array_3 + 5

array([[ 6,  7,  8,  9, 10],
       [10,  8,  7,  9,  7],
       [ 6,  7,  8,  9, 10]])

In [33]:
#cool, similarly works for substraction, multiply or division

In [36]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [37]:
array_3*2

array([[ 2,  4,  6,  8, 10],
       [10,  6,  4,  8,  4],
       [ 2,  4,  6,  8, 10]])

In [38]:
array_3/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [2.5, 1.5, 1. , 2. , 1. ],
       [0.5, 1. , 1.5, 2. , 2.5]])

In [39]:
#sum function (note sum is not same as add, as add uses 2 arrays or array+scaler value, sum sums of element of given array)

#np.sum(array, axis=0_or_1, ..other optional params..)

In [41]:
array_1

array([[1, 2, 3, 3, 3]])

In [40]:
np.sum(array_1)

12

In [42]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [43]:
np.sum(array_3) #if no axis is provided, by default all elements are summed up

46

In [44]:
#summing only on axis 0 (meaning column after column: sum-column1, sum-column2,sum-column3...so on)

np.sum(array_3, axis=0)

array([ 7,  7,  8, 12, 12])

In [45]:
#summing only on axis 1 (meaning row after row: sum-row1, sum-row2,sum-row3...so on)

np.sum(array_3,axis=1)


array([15, 16, 15])

In [46]:
#cumsum - same as sum, but its a cumulative sum

#np.cumsum(array, axis, other param)
#if axis is not provided,then by default all elements are resulted with addition of (sum of previous element)

In [48]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [47]:
np.cumsum(array_3)

array([ 1,  3,  6, 10, 15, 20, 23, 25, 29, 31, 32, 34, 37, 41, 46])

In [49]:
np.cumsum(array_3, axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  5,  5,  8,  7],
       [ 7,  7,  8, 12, 12]])

In [50]:
np.cumsum(array_3, axis=1)

array([[ 1,  3,  6, 10, 15],
       [ 5,  8, 10, 14, 16],
       [ 1,  3,  6, 10, 15]])

In [51]:
#cool

In [52]:
#now, lets see mean, amax and amin


#np.mean(array, axis, ..other optional param..)
#np.amax(array, axis, ..other optional param..)
#np.amin(array, axis, ..other optional params..)

In [54]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [53]:
np.mean(array_3)

3.066666666666667

In [55]:
np.mean(array_3,axis=0) #i.e.mean of column1,column2,column3..so on (by row)

array([2.33333333, 2.33333333, 2.66666667, 4.        , 4.        ])

In [56]:
#similarly, for axis=1, means mean of row1,row2,row3..so on (by columns)

np.mean(array_3, axis=1)

array([3. , 3.2, 3. ])

In [57]:
#now, lets see max and min function

In [58]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [62]:
np.amax(array_3)

5

In [61]:
np.max(array_3)

5

In [63]:
#hmm, looks like amax and max are same, we may find out differences later, but looks same as of now

In [64]:
np.amin(array_3)

1

In [65]:
np.min(array_3)

1

In [66]:
#hmm, looks like amin and min are same too, we may find out differences later, but looks same as of now

In [67]:
np.amax(array_3, axis=0)

array([5, 3, 3, 4, 5])

In [68]:
np.amax(array_3, axis=1)

array([5, 5, 5])

In [69]:
#cool,min works the same way,lets see

In [70]:
array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [71]:
np.amin(array_3, axis=0)

array([1, 2, 2, 4, 2])

In [73]:
np.min(array_3, axis=1)

array([1, 2, 1])

In [74]:
array_2

array([[1, 2, 3],
       [4, 5, 5],
       [3, 2, 4],
       [2, 1, 2],
       [3, 4, 5]])

In [75]:
np.min(array_2, axis=0)

array([1, 1, 2])

In [76]:
np.amin(array_2, axis=1)

array([1, 4, 2, 1, 3])

In [77]:
#cool stuff

In [81]:
#we can also find statistical thing this way, lets see standard-deviation

array_3

array([[1, 2, 3, 4, 5],
       [5, 3, 2, 4, 2],
       [1, 2, 3, 4, 5]])

In [80]:
np.std(array_3)

1.339983416149452

In [79]:
np.std(array_3, axis=0)

array([1.88561808, 0.47140452, 0.47140452, 0.        , 1.41421356])

In [82]:
np.std(array_3, axis=1)

array([1.41421356, 1.16619038, 1.41421356])