In [1]:
##IO functions:

#11. numpy.loadtxt(fname, dtype=<class 'float'7gt;, comments='#', delimiter=None, converters=None, 
#                  skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes')
#12. np.count_nonzero(array, axis=none, ..)
#13. np.genfromtxt
#14. np.load (this works with npy & npz extensions, will se later)
#15. np.savetxt (filename, array, delimiter,...)

In [3]:
import numpy as np

In [5]:
np.loadtxt('Cars n dealers and price_JLT'.XLS)

AttributeError: 'str' object has no attribute 'XLS'

In [ ]:
#below is the file 'tfl-daily-cycle-hires'  that tells us bikes hired by day for almost 10 years

In [15]:
np.loadtxt('tfl-daily-cycle-hires.txt', delimiter=',', skiprows=1, usecols=(1))

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [16]:
#cool, so from the file, we pulled of 2nd column values (Number of Bicycle Hires), as an array
# now it can be sliced and diced for analysis

#note: since the (txt/csv) file is pulled from the location which is same as of this jupyter workbook...
#...... only file name was needed, otherwise, we need compete address of file (lets move the file & see)

In [17]:
np.loadtxt('tfl-daily-cycle-hires.txt', delimiter=',', skiprows=1, usecols=(1))

FileNotFoundError: tfl-daily-cycle-hires.txt not found.

In [18]:
#cool, as the file is moved, it was not found, so above error is good to see

In [31]:
np.loadtxt(r"C:\Users\Ankur\Desktop\tfl-daily-cycle-hires.txt", delimiter=',', skiprows=1, usecols=(1))

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [ ]:
# so note few things here:...

# 'r' is added at start of file name , coz we got unicide error, and to avoid it convert string into raw string...
#... so use - r"C:\Users\Ankur\Desktop\tfl-daily-cycle-hires.txt"

# alternatively we could have used - "C:\\Users\\Ankur\\Desktop\\tfl-daily-cycle-hires.txt" i.e doulble \\..
# ...in place of single\

In [32]:
np.loadtxt('tfl-daily-cycle-hires.csv', delimiter=',', skiprows=1, usecols=(1))

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [33]:
#cool, so csv also does work the same way

#lets assign [32 to x]

In [34]:
x=np.loadtxt('tfl-daily-cycle-hires.csv', delimiter=',', skiprows=1, usecols=(1))

In [35]:
x

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [1]:
#few things to note, before we analyze it

# its skiprows instead of skiprow
# its usecols instaed of usecols, value is passed here in tuple

In [7]:
x=np.loadtxt('tfl-daily-cycle-hires.csv', delimiter=',',skiprows=1, usecols=(1))
x

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [5]:
#so, lets see some functions to slice n dice

In [6]:
#syntax - np.count_nonzero(array,axis,..others)

In [8]:
np.count_nonzero(x) #since x is 1d array, so no need to define axis

4081

In [15]:
np.count(x) #JLT, just wanted to check if count is a function in arrays, looks like its not

AttributeError: module 'numpy' has no attribute 'count'

In [9]:
#lets see max, min and avg number of bikes hired in a day

In [10]:
np.amax(x) # max bikes hired in a single day

73094.0

In [11]:
np.max(x)

73094.0

In [12]:
#since amax and max are same

In [13]:
np.min(x) # min bikes hired in a single day

2764.0

In [16]:
np.sum(x)/np.count_nonzero(x) #calculating average bikes hired in a day

26261.932124479295

In [17]:
#average can also be calculated using mean

np.mean(x)

26261.932124479295

In [18]:
#or

x.mean()

26261.932124479295

In [19]:
x.std()

9740.107235227775

In [20]:
#again, picking the file (.txt) from desktop location

In [24]:
np.loadtxt('C:\Users\Ankur\Desktop\tfl-daily-cycle-hires.txt', delimiter=',', skiprows=1, usecols=(1))

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (2907708945.py, line 1)

In [22]:
#ok, we get unicode error (so use \\ or r as prefix)

In [25]:
np.loadtxt('C:\\Users\\Ankur\\Desktop\\tfl-daily-cycle-hires.txt', delimiter=',', skiprows=1, usecols=(1))

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [26]:
# or use 'r' to convert to raw-string

In [27]:
np.loadtxt(r'C:\Users\Ankur\Desktop\tfl-daily-cycle-hires.txt', delimiter=',', skiprows=1, usecols=(1))

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [28]:
#lets look at other input frunctions - 'gen from txt' and 'load' functions (HW)

#np.genfromtxt
#np.load

In [29]:
#output(ing) the file, basically saving it somewhere as text/csv (use function - np.savetxt)

#syntax - np.savetxt(FileName, array, ...others...)

#again, just the file name if saving at the same place as of this jupyter workbook, otherwise specify complete path

In [30]:
x

array([ 6897.,  5564.,  4303., ..., 32539., 39889., 34070.])

In [31]:
#lets save it as test  output

In [32]:
np.savetxt('test_output.txt',x)

In [33]:
#cool, now lets chek the folder (hang on...)
#.
#.
#.
#yay, its there

#lets save it to some other location (not sure if we will need 'r' or \\), lets do it


In [37]:
np.savetxt('C:\Users\Ankur\Desktop\test_output.txt',x)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3427831625.py, line 1)

In [35]:
#yup, as expected, unicode error

In [42]:
np.savetxt('C:\\Users\\Ankur\\Desktop\\test_output.csv',x)

In [43]:
#if above file is open, you get permission error

In [ ]:
#cool, much more on pandas, so lets meet there