# Challenge Questions - NumPy

# Instructions:
• Please ensure you don't overwrite any existing cells. Add new cells below by pressing ALT+ENTER

• Attempt all of the questions

• You are encouraged to look online for help should you need it

# 

## Q1: Import the NumPy library

In [1]:
#Type your code here
import numpy as np


## Q2: Create a 5 row by 3 column array that contains only the value 7

In [ ]:
# Type your code here


In [2]:
np.full((5,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

## Q3: Create a 3 row by 4 column array that contains evenly spaced values between 0-100

In [ ]:
# Type your code here


In [5]:
x=np.linspace(0,100,12)
x

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [6]:
x.reshape(3,4)

array([[  0.        ,   9.09090909,  18.18181818,  27.27272727],
       [ 36.36363636,  45.45454545,  54.54545455,  63.63636364],
       [ 72.72727273,  81.81818182,  90.90909091, 100.        ]])

In [8]:
#or simply

x=np.linspace(0,100, num=12).reshape(3,4)
x

array([[  0.        ,   9.09090909,  18.18181818,  27.27272727],
       [ 36.36363636,  45.45454545,  54.54545455,  63.63636364],
       [ 72.72727273,  81.81818182,  90.90909091, 100.        ]])

In [ ]:
#cool

## Q4 Take the shape from Q3 and transform it so that the numbers increment down the columns rather than along the rows

In [ ]:
# Type your code here
#looks like its asking to cumulate along axis 1, lets do before looking up the solution

In [9]:
np.cumsum(x,axis=1)

array([[  0.        ,   9.09090909,  27.27272727,  54.54545455],
       [ 36.36363636,  81.81818182, 136.36363636, 200.        ],
       [ 72.72727273, 154.54545455, 245.45454545, 345.45454545]])

In [ ]:
#hmm, no not this, it means number comes in columns,rather than rows, so use transpose (but good call)

In [10]:
x=np.linspace(0,100, num=12)
x

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [13]:
x.reshape(3,4).transpose()

array([[  0.        ,  36.36363636,  72.72727273],
       [  9.09090909,  45.45454545,  81.81818182],
       [ 18.18181818,  54.54545455,  90.90909091],
       [ 27.27272727,  63.63636364, 100.        ]])

In [ ]:
#cool stuff

## Q5 From the 2D array stored in the variable "a" below use slicing to return the below segment

In [14]:
# Run this cell first
a = np.linspace(0,24,num=25).reshape(5,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [19]:
# Type your code here
a[2:4,1:4]

array([[11., 12., 13.],
       [16., 17., 18.]])

In [ ]:
#so the concept is a(x,y), first slice for x(2:4), then for y(1:4)

## Q6: Return only elements that are greater than 12 from the same array "a" as Q5

In [27]:
# Type your code here
# recalling array(a) for screen visibility
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [25]:
#to get the boolean (true/false) use:

q5=a>12
q5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [26]:
#to get the values( or Q5)

Q5=a[a>12]
Q5

array([13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

## Q7: There is a file called 'tfl-daily-cycle-hires-2018.csv' saved in the same directory as this notebook. We will be needing only the "Number of Bicycle Hires" data.
1. Load and store it in a variable called tfl_18 and check the shape of the array. 
2. Check the shape of the array
3. Change the array to be a 2D array of shape (365,1)

### This file contains the daily cycle hire numbers for the year 2018.

### Hint: Consider the use of appropriate optional arguments in whatever function you choose to use.

In [43]:
# Load the data here (note: CSV is comma seperated, athough not visible, but choose deliter as ',')

tfl_18=np.loadtxt('tfl-daily-cycle-hires-2018.csv', delimiter=',', skiprows=1, usecols=(1))


In [44]:
# Check the shape here

tfl_18.shape

(365,)

In [54]:
# Change the shape here

tfl_18 = tfl_18.reshape(365,1)

In [55]:
tfl_18.shape

(365, 1)

## Q8: There is a file called 'tfl-daily-cycle-hires-2019.csv' saved in the same directory as this notebook. We will be needing only the "Number of Bicycle Hires" data.
1. Load and store it in a variable called tfl_19 and check the shape of the array. 
2. Check the shape of the array
3. Change the array to be a 2D array of shape (365,1)

In [56]:
# Load the data here
tfl_19=np.loadtxt('tfl-daily-cycle-hires-2019.csv', delimiter=',', skiprows=1, usecols=(1))

In [57]:
# Check the shape here
tfl_19.shape

(365,)

In [58]:
# Change the shape here
tfl_19= tfl_19.reshape(365,1)

In [59]:
tfl_19.shape

(365, 1)

## Q9: Create a new array called tfl_1819 that contains the two arrays tfl_18 and tfl_19 concatenated together on the 1 axis. The shape of tfl_1819 should be (365, 2)

In [60]:
# Concatenate the arrays here

tfl_1819 = np.concatenate((tfl_18, tfl_19), axis=1)

In [61]:
# Check the shape here
tfl_1819.shape

(365, 2)

In [62]:
#just checking, .....yeah, it is 365 by 2

tfl_1819

array([[10235., 14148.],
       [14394., 19746.],
       [20265., 21552.],
       [17543., 20863.],
       [21759., 13907.],
       [13920., 14262.],
       [12259., 25668.],
       [23374., 27757.],
       [24683., 26568.],
       [26787., 26022.],
       [25222., 26378.],
       [24696., 16750.],
       [17512., 16304.],
       [15070., 28097.],
       [19161., 29413.],
       [26921., 24500.],
       [26934., 26053.],
       [26471., 25525.],
       [25799., 16653.],
       [ 9398., 16803.],
       [ 5859., 26567.],
       [26337., 23083.],
       [26003., 25406.],
       [20206., 24357.],
       [28189., 24198.],
       [26430., 15062.],
       [14472., 10596.],
       [17512., 25859.],
       [26371., 24732.],
       [28002., 25482.],
       [24117., 23487.],
       [25525., 12841.],
       [25331., 14136.],
       [ 8975., 14637.],
       [13833., 18254.],
       [23898., 25682.],
       [25349., 26197.],
       [25388., 26703.],
       [25791., 17468.],
       [21037., 17439.],


## Q10 Perform the following operations on the concatenated array tfl_1819:
1. Find the sum of the columns, this shoe the total bike hires for 2018 and 2019
2. Find the average number of bike hires for both columns, this will show the average bike hires for 2018 and 2019
3. Find the maximum number of bike hires in both columns,  this will show the maximum bike figure for a single day in 2018 and 2019

In [63]:
# Sum the columns here

np.sum(tfl_1819, axis=0)

array([10567540., 10424955.])

In [64]:
# Find the average of the columns here
np.mean(tfl_1819, axis=0)

array([28952.16438356, 28561.52054795])

In [65]:
# Find the maximum of both columns here
np.amax(tfl_1819, axis=0)


array([46084., 44668.])

In [ ]:
#amazing, all done here, ltes move to exciting pandas...